version: "3.9"

volumes:
  buycut_data:
    name: buycut_data

services:
  postgres:
    image: postgres:14-alpine
    restart: always
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DATABASE}
    volumes:
      - buycut_data:/var/lib/postgresql/data
