// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package initializer

import (
	"github.com/ariefro/buycut-api/config"
	"github.com/ariefro/buycut-api/database"
	"github.com/ariefro/buycut-api/internal/company"
	"github.com/ariefro/buycut-api/internal/server"
	"github.com/google/wire"
)

// Injectors from initializer.go:

func InitializedServer() error {
	configConfig := config.NewLoadConfig()
	db := database.NewConnectPostgres(configConfig)
	repository := company.NewRepository(db)
	service := company.NewService(repository)
	controller := company.NewController(service)
	error2 := server.NewFiberServer(configConfig, controller)
	return error2
}

// initializer.go:

var companySet = wire.NewSet(company.NewRepository, company.NewService, company.NewController)
